using System.Data;
using System.IO;
using System.Xml.Linq;
using AutoReportWizard.Models;
using Microsoft.Reporting.WinForms;

namespace AutoReportWizard.Services;

/// <summary>
/// Renders an RDLC report definition via the WinForms ReportViewer control using
/// an in-memory XML stream. No physical temp files are created at any point.
/// </summary>
public static class ReportPreviewService
{
    /// <summary>
    /// Serializes the RDLC XML document generated by <see cref="RdlcXmlEngine"/> into a
    /// <see cref="MemoryStream"/> and rewinds it to position 0 so the caller can pass it
    /// directly to <see cref="LocalReport.LoadReportDefinition(Stream)"/>.
    /// </summary>
    /// <param name="def">The fully populated report definition.</param>
    /// <param name="ct">Cancellation token forwarded from the calling async context.</param>
    /// <returns>
    /// A <see cref="MemoryStream"/> whose <see cref="Stream.Position"/> is 0 and which
    /// contains the UTF-8 encoded RDLC XML. The caller owns the stream and is responsible
    /// for disposing it after <see cref="LocalReport.LoadReportDefinition"/> has been called
    /// (i.e., after <see cref="ReportViewer.RefreshReport"/> has completed).
    /// </returns>
    public static async Task<MemoryStream> SerializeToStreamAsync(
        ReportDefinition def,
        CancellationToken ct = default)
    {
        XDocument document = RdlcXmlEngine.GenerateRdlcXml(def);

        // MemoryStream is not disposed here — the caller (ViewModel) holds and
        // later disposes it after the ReportViewer has consumed the definition.
        var memoryStream = new MemoryStream();
        await document.SaveAsync(memoryStream, SaveOptions.None, ct);

        // CRITICAL: rewind to the beginning so LoadReportDefinition reads from byte 0.
        memoryStream.Position = 0;

        return memoryStream;
    }

    /// <summary>
    /// Binds an in-memory RDLC stream and a <see cref="DataTable"/> to a
    /// <see cref="ReportViewer"/> instance and triggers a render cycle.
    /// </summary>
    /// <param name="viewer">The WinForms ReportViewer to render into.</param>
    /// <param name="rdlcStream">
    /// The RDLC XML stream produced by <see cref="SerializeToStreamAsync"/>.
    /// Must be seeked to position 0 before calling this method.
    /// </param>
    /// <param name="data">The DataTable returned by the database query.</param>
    /// <param name="parameters">
    /// Optional collection of dynamic parameters to pass to the report.
    /// </param>
    /// <exception cref="ArgumentNullException">
    /// Thrown if <paramref name="rdlcStream"/> is null.
    /// </exception>
    public static void RenderLocalReportFromStream(
        ReportViewer viewer,
        Stream rdlcStream,
        DataTable data,
        IEnumerable<DynamicParameter>? parameters = null)
    {
        if (rdlcStream is null)
            throw new ArgumentNullException(nameof(rdlcStream),
                "RDLC stream must not be null. Ensure SerializeToStreamAsync has completed.");

        viewer.ProcessingMode = ProcessingMode.Local;

        // Clear any previously-loaded report path so that LoadReportDefinition
        // takes full effect (mixing ReportPath and LoadReportDefinition can cause
        // the viewer to ignore the stream on subsequent renders).
        viewer.LocalReport.ReportPath = string.Empty;

        // Guarantee the stream is at the start position before loading.
        if (rdlcStream.CanSeek)
            rdlcStream.Position = 0;

        // ═══════════════════════════════════════════════════════════════════════════
        // DIAGNOSTIC XML DUMP: Save exact RDLC being fed to the engine
        // ═══════════════════════════════════════════════════════════════════════════
        try
        {
            string debugRdlcPath = Path.Combine(Path.GetTempPath(), "Debug_AutoReportWizard.rdlc");
            
            using (var fileStream = new FileStream(debugRdlcPath, FileMode.Create, FileAccess.Write, FileShare.Read))
            {
                rdlcStream.CopyTo(fileStream);
            }
            
            // Rewind stream back to start after diagnostic copy
            if (rdlcStream.CanSeek)
                rdlcStream.Position = 0;
            
            System.Diagnostics.Debug.WriteLine($"✓ Diagnostic RDLC dumped to: {debugRdlcPath}");
        }
        catch (Exception dumpEx)
        {
            // Don't fail rendering if diagnostic dump fails
            System.Diagnostics.Debug.WriteLine($"⚠️  Failed to dump diagnostic RDLC: {dumpEx.Message}");
        }

        // ═══════════════════════════════════════════════════════════════════════════
        // DATASET NAME VERIFICATION: Ensure binding name matches RDLC definition
        // ═══════════════════════════════════════════════════════════════════════════
        const string DATA_SOURCE_NAME = "MainDataSet";
        
        // Log dataset binding information for diagnostic purposes
        System.Diagnostics.Debug.WriteLine("═══ DATASET BINDING DIAGNOSTICS ═══");
        System.Diagnostics.Debug.WriteLine($"DataSource Name: {DATA_SOURCE_NAME}");
        System.Diagnostics.Debug.WriteLine($"DataTable Name: {data.TableName}");
        System.Diagnostics.Debug.WriteLine($"Column Count: {data.Columns.Count}");
        System.Diagnostics.Debug.WriteLine($"Row Count: {data.Rows.Count}");
        System.Diagnostics.Debug.WriteLine("Column Names:");
        
        foreach (DataColumn col in data.Columns)
        {
            System.Diagnostics.Debug.WriteLine($"  • {col.ColumnName} ({col.DataType.Name})");
        }
        
        viewer.LocalReport.LoadReportDefinition(rdlcStream);
        viewer.LocalReport.DataSources.Clear();
        
        // CRITICAL: The DataSource name "MainDataSet" MUST exactly match the
        // <DataSet Name="MainDataSet"> generated in RdlcXmlEngine.BuildDataSets().
        // Any mismatch (even whitespace or case) will cause LocalProcessingException:
        // "A data source instance has not been supplied for the data source 'MainDataSet'."
        viewer.LocalReport.DataSources.Add(new ReportDataSource(DATA_SOURCE_NAME, data));
        
        System.Diagnostics.Debug.WriteLine($"✓ DataSource '{DATA_SOURCE_NAME}' bound successfully");

        if (parameters is not null)
        {
            var reportParams = parameters
                .Where(p => !string.IsNullOrWhiteSpace(p.RdlcParameterName))
                .Select(p => 
                {
                    string? safeValue = p.Value == " " ? null : (string.IsNullOrWhiteSpace(p.Value) ? null : p.Value.Trim());
                    System.Diagnostics.Debug.WriteLine($"  Parameter: {p.RdlcParameterName} = {safeValue ?? "(null)"}");
                    return new Microsoft.Reporting.WinForms.ReportParameter(p.RdlcParameterName, safeValue);
                })
                .ToArray();

            if (reportParams.Length > 0)
            {
                System.Diagnostics.Debug.WriteLine($"✓ Setting {reportParams.Length} report parameter(s)");
                viewer.LocalReport.SetParameters(reportParams);
            }
        }

        System.Diagnostics.Debug.WriteLine("Triggering RefreshReport()...");
        viewer.RefreshReport();
        System.Diagnostics.Debug.WriteLine("✓ Report rendered successfully");
    }
}
